stages:
  - test-and-build

Test:
  image: golang:1.14
  stage: test-and-build
  script:
    - go test ./...

Build:
  image: docker:stable
  stage: test-and-build
  script:
    - go build -mod vendor github.com/justinhbaker3/todo-list/cmd/todo-list
